-- Esquema relacional de Firmeza para PostgreSQL.
-- Puede ejecutarse sobre una base vacía o sobre una instancia que ya tenga
-- estas tablas: IF NOT EXISTS conserva las tablas y los datos existentes.

CREATE TABLE IF NOT EXISTS public."Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "DocumentType" character varying(20) NOT NULL,
    "DocumentNumber" character varying(30) NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Address" character varying(150),
    "Phone" character varying(30),
    "Email" character varying(150),
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ProductCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(250),
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Code" character varying(30) NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Description" character varying(500),
    "UnitOfMeasure" character varying(30) NOT NULL,
    "UnitPrice" numeric(18, 2) NOT NULL,
    "CurrentStock" numeric(18, 3) NOT NULL,
    "MinimumStock" numeric(18, 3) NOT NULL,
    "IsActive" boolean NOT NULL,
    "ProductCategoryId" integer NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_ProductCategories_ProductCategoryId"
        FOREIGN KEY ("ProductCategoryId") REFERENCES public."ProductCategories" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public."Sales" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "SaleNumber" character varying(30) NOT NULL,
    "SaleDate" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL,
    "DeliveryAddress" character varying(500),
    "Subtotal" numeric(18, 2) NOT NULL,
    "Tax" numeric(18, 2) NOT NULL,
    "Total" numeric(18, 2) NOT NULL,
    "CustomerId" integer NOT NULL,
    CONSTRAINT "PK_Sales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sales_Customers_CustomerId"
        FOREIGN KEY ("CustomerId") REFERENCES public."Customers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public."SaleDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Quantity" numeric(18, 3) NOT NULL,
    "UnitPrice" numeric(18, 2) NOT NULL,
    "Subtotal" numeric(18, 2) NOT NULL,
    "SaleId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    CONSTRAINT "PK_SaleDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SaleDetails_Sales_SaleId"
        FOREIGN KEY ("SaleId") REFERENCES public."Sales" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SaleDetails_Products_ProductId"
        FOREIGN KEY ("ProductId") REFERENCES public."Products" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public."AspNetUsers" (
    "Id" text NOT NULL,
    "CustomerId" integer,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_Customers_CustomerId"
        FOREIGN KEY ("CustomerId") REFERENCES public."Customers" ("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public."AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Customers_DocumentType_DocumentNumber"
    ON public."Customers" ("DocumentType", "DocumentNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_Code"
    ON public."Products" ("Code");
CREATE INDEX IF NOT EXISTS "IX_Products_ProductCategoryId"
    ON public."Products" ("ProductCategoryId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Sales_SaleNumber"
    ON public."Sales" ("SaleNumber");
CREATE INDEX IF NOT EXISTS "IX_Sales_CustomerId"
    ON public."Sales" ("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_SaleDetails_SaleId"
    ON public."SaleDetails" ("SaleId");
CREATE INDEX IF NOT EXISTS "IX_SaleDetails_ProductId"
    ON public."SaleDetails" ("ProductId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUsers_CustomerId"
    ON public."AspNetUsers" ("CustomerId");
CREATE INDEX IF NOT EXISTS "EmailIndex"
    ON public."AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex"
    ON public."AspNetUsers" ("NormalizedUserName");
CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex"
    ON public."AspNetRoles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId"
    ON public."AspNetRoleClaims" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId"
    ON public."AspNetUserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId"
    ON public."AspNetUserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId"
    ON public."AspNetUserRoles" ("RoleId");
